export const GET_PAYMENTS = "GET_PAYMENTS";
export const PAYMENT_LOAD_SUCCESS = "PAYMENT_LOAD_SUCCESS";
export const TOGGLE_PAYMENT = "TOGGLE_PAYMENT";
export const PAYMENTS_LOADING = "PAYMENTS_LOADING";
export const REJECT_PAYMENT = "REJECT_PAYMENT";
export const UPDATE_PAYMENT_NOTE = "UPDATE_PAYMENT_NOTE";
export const ON_PAYMENT_NOTES_CHANGE = "ON_PAYMENT_NOTES_CHANGE";


