export const OBJECTIONS_LOADED = "OBJECTIONS_LOADED";
export const ON_OBJECTION_APPROVAL_CHANGE = "ON_OBJECTION_APPROVAL_CHANGE";
export const ON_OBJECTION_NOTES_CHANGE = "ON_OBJECTION_NOTES_CHANGE";
export const APPROVAL_STATE = {
  APPROVED: 'approved',
  REJECTED: 'rejected',
  PENDING: 'pending',
};