swagger: '2.0'
info:
  title: REFERENCE API
  version: 1.0.0
  description: <p>This is micro service api for Gov Election Nomination App</p>
host: localhost:9001
basePath: /
paths:
  $ref: ./api-docs/paths/index.yaml
parameters:
  $ref: ./api-docs/parameters.yaml