merchantId:
  name: merchantId
  description: Unique identifier of merchant
  in: path
  required: true
  type: string
shiftId:
  name: shiftId
  description: Unique identifier of an employee shift
  in: path
  required: true
  type: string
limit:
  name: limit
  description: Limit value of pagination
  in: query
  required: false
  type: integer

