--
-- EC-TEAM V1.1
--

DROP DATABASE IF EXISTS EC_TEAM;

CREATE DATABASE IF NOT EXISTS EC_TEAM CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE EC_TEAM;

CREATE TABLE IF NOT EXISTS TEAM(
	ID VARCHAR(36) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	SYMBOL VARCHAR(20),
	TELEPHONE VARCHAR(100),
	FAX VARCHAR(10),
	NAME_OF_AUTHORIZED_MEMBER VARCHAR(100),
	ADDRESS_OF_AUTHORIZED_MEMBER VARCHAR(300)
)ENGINE=INNODB;