export const GET_ELECTIONS = "GET_ELECTIONS";
export const CREATE_ELECTION_MODULE = "CREATE_ELECTION_MODULE";
export const CLEAR_ELECTION_MODULE = "CLEAR_ELECTION_MODULE";
export const UPDATE_ELECTION_MODULE = "UPDATE_ELECTION_MODULE";
export const SAVE_ELECTION_MODULE = "SAVE_ELECTION_MODULE";
export const GET_APPROVED_ELECTION_MODULE = "GET_APPROVED_ELECTION_MODULE";
export const GET_PENDING_ELECTION_MODULE = "GET_PENDING_ELECTION_MODULE";
export const GET_REJECTED_ELECTION_MODULE = "GET_REJECTED_ELECTION_MODULE";
export const GET_ELECTION_TEMPLATE_DATA = "GET_ELECTION_TEMPLATE_DATA";
export const GET_DELETED_ELECTION_MODULE = "GET_DELETED_ELECTION_MODULE";
export const GET_ALL_ELECTION_TEMPLATES = "GET_ALL_ELECTION_TEMPLATES";
export const ELECTION_TEMPLATE_REVIEW_DATA = "ELECTION_TEMPLATE_REVIEW_DATA";
export const ON_ELECTION_TEMPLATE_APPROVAL_CHANGE = "ON_ELECTION_TEMPLATE_APPROVAL_CHANGE";
export const RECEIVE_APPROVED_ELECTION_TEMPLATES = "RECEIVE_APPROVED_ELECTION_TEMPLATES";
export const RECIVE_PENDING_ELECTION_MODULE = "RECIVE_PENDING_ELECTION_MODULE";

export const APPROVAL_STATE = {
    APPROVE: 'APPROVE',
    REJECT: 'REJECT',
    PENDING: 'PENDING',
  };
