name: Platformer Generated nomination Build
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/nomination
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_D9CFF7DF_3A4B_4400_A8F4_212E1647BC40 }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file ./client/Dockerfile ./client --build-arg API_BASE_URL=https://apim-gateway.training.opensource.lk/nominations/0.9 --build-arg APP_PDF_GENARATION_SERVICE_URL=https://apim-gateway.training.opensource.lk/nominations/0.9 --build-arg APP_AUTH_BASE_URL=https://nominations.training.opensource.lk --build-arg APP_NOMINATION_URL=https://nominations.training.opensource.lk
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_92DA1243_81F5_47E6_B824_A409AD65A74D}}
          project-id: ${{secrets.PROJECT_ID_92DA1243_81F5_47E6_B824_A409AD65A74D}}
          token: ${{secrets.AUTOGENERATED_CICD_92DA1243_81F5_47E6_B824_A409AD65A74D}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 8a8215cc-cffc-4c92-a1fd-1b963392d247
