name: Platformer Generated ui-stag-push Build
'on':
  push:
    tags:
      - stag*
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/nomination
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_65D8B6B3_04F8_46AE_B449_2A1FFE571812 }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file /client/Staging.Dockerfile ./client/
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_92DA1243_81F5_47E6_B824_A409AD65A74D}}
          project-id: ${{secrets.PROJECT_ID_92DA1243_81F5_47E6_B824_A409AD65A74D}}
          token: ${{secrets.AUTOGENERATED_CICD_92DA1243_81F5_47E6_B824_A409AD65A74D}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: e66846c7-3a19-4e95-a634-9a01a2494ec0
